package com.wistronits.wistlotto.repository;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.wistronits.wistlotto.model.EmpInfoModel;

@Mapper
public interface LottoRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_emp_info
	 * @mbg.generated
	 */
	List<EmpInfoModel> getEmpList();
}