package com.wistronits.wistlotto.repository.tables;

import com.wistronits.wistlotto.model.tables.TDeptInfo;
import com.wistronits.wistlotto.model.tables.TDeptInfoCriteria;
import com.wistronits.wistlotto.model.tables.TDeptInfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TDeptInfoRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_dept_info
	 * 
	 * @mbg.generated
	 */
	long countByExample(TDeptInfoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_dept_info
	 * 
	 * @mbg.generated
	 */
	int deleteByExample(TDeptInfoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_dept_info
	 * 
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(TDeptInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_dept_info
	 * 
	 * @mbg.generated
	 */
	int insert(TDeptInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_dept_info
	 * 
	 * @mbg.generated
	 */
	int insertSelective(TDeptInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_dept_info
	 * 
	 * @mbg.generated
	 */
	List<TDeptInfo> selectByExample(TDeptInfoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_dept_info
	 * 
	 * @mbg.generated
	 */
	TDeptInfo selectByPrimaryKey(TDeptInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_dept_info
	 * 
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TDeptInfo record, @Param("example") TDeptInfoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_dept_info
	 * 
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TDeptInfo record, @Param("example") TDeptInfoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_dept_info
	 * 
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TDeptInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_dept_info
	 * 
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TDeptInfo record);
}