package com.wistronits.wistlotto.repository.tables;

import com.wistronits.wistlotto.model.tables.TPrizeGroupInfo;
import com.wistronits.wistlotto.model.tables.TPrizeGroupInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TPrizeGroupInfoRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prize_group_info
     *
     * @mbg.generated
     */
    long countByExample(TPrizeGroupInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prize_group_info
     *
     * @mbg.generated
     */
    int deleteByExample(TPrizeGroupInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prize_group_info
     *
     * @mbg.generated
     */
    int insert(TPrizeGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prize_group_info
     *
     * @mbg.generated
     */
    int insertSelective(TPrizeGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prize_group_info
     *
     * @mbg.generated
     */
    List<TPrizeGroupInfo> selectByExample(TPrizeGroupInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prize_group_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPrizeGroupInfo record, @Param("example") TPrizeGroupInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prize_group_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPrizeGroupInfo record, @Param("example") TPrizeGroupInfoCriteria example);
}