package com.wistronits.wistlotto.repository.tables;

import com.wistronits.wistlotto.domain.tables.TSysInfo;
import com.wistronits.wistlotto.domain.tables.TSysInfoCriteria;
import com.wistronits.wistlotto.domain.tables.TSysInfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TSysInfoRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_info
     *
     * @mbg.generated
     */
    long countByExample(TSysInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_info
     *
     * @mbg.generated
     */
    int deleteByExample(TSysInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TSysInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_info
     *
     * @mbg.generated
     */
    int insert(TSysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_info
     *
     * @mbg.generated
     */
    int insertSelective(TSysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_info
     *
     * @mbg.generated
     */
    List<TSysInfo> selectByExample(TSysInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_info
     *
     * @mbg.generated
     */
    TSysInfo selectByPrimaryKey(TSysInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TSysInfo record, @Param("example") TSysInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TSysInfo record, @Param("example") TSysInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSysInfo record);
}