package com.wistronits.wistlotto.model.tables;

import java.io.Serializable;

public class TDeptInfoKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_dept_info.dept_id
	 * @mbg.generated
	 */
	private String deptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_dept_info
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_dept_info.dept_id
	 * @return  the value of t_dept_info.dept_id
	 * @mbg.generated
	 */
	public String getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_dept_info.dept_id
	 * @param deptId  the value for t_dept_info.dept_id
	 * @mbg.generated
	 */
	public void setDeptId(String deptId) {
		this.deptId = deptId == null ? null : deptId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_dept_info
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		TDeptInfoKey other = (TDeptInfoKey) that;
		return (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_dept_info
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_dept_info
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", deptId=").append(deptId);
		sb.append("]");
		return sb.toString();
	}
}