package com.wistronits.wistlotto.model.tables;

import java.io.Serializable;

public class TDeptInfo extends TDeptInfoKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_dept_info.dept_name
	 * @mbg.generated
	 */
	private String deptName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_dept_info
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_dept_info.dept_name
	 * @return  the value of t_dept_info.dept_name
	 * @mbg.generated
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_dept_info.dept_name
	 * @param deptName  the value for t_dept_info.dept_name
	 * @mbg.generated
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName == null ? null : deptName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_dept_info
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		TDeptInfo other = (TDeptInfo) that;
		return (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
				&& (this.getDeptName() == null ? other.getDeptName() == null
						: this.getDeptName().equals(other.getDeptName()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_dept_info
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
		result = prime * result + ((getDeptName() == null) ? 0 : getDeptName().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_dept_info
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", deptName=").append(deptName);
		sb.append("]");
		return sb.toString();
	}
}