package com.wistronits.wistlotto.model.tables;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TEmpInfoCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    public TEmpInfoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEmpIdIsNull() {
            addCriterion("emp_id is null");
            return (Criteria) this;
        }

        public Criteria andEmpIdIsNotNull() {
            addCriterion("emp_id is not null");
            return (Criteria) this;
        }

        public Criteria andEmpIdEqualTo(String value) {
            addCriterion("emp_id =", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotEqualTo(String value) {
            addCriterion("emp_id <>", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdGreaterThan(String value) {
            addCriterion("emp_id >", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdGreaterThanOrEqualTo(String value) {
            addCriterion("emp_id >=", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLessThan(String value) {
            addCriterion("emp_id <", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLessThanOrEqualTo(String value) {
            addCriterion("emp_id <=", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLike(String value) {
            addCriterion("emp_id like", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotLike(String value) {
            addCriterion("emp_id not like", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdIn(List<String> values) {
            addCriterion("emp_id in", values, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotIn(List<String> values) {
            addCriterion("emp_id not in", values, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdBetween(String value1, String value2) {
            addCriterion("emp_id between", value1, value2, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotBetween(String value1, String value2) {
            addCriterion("emp_id not between", value1, value2, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpCnameIsNull() {
            addCriterion("emp_cname is null");
            return (Criteria) this;
        }

        public Criteria andEmpCnameIsNotNull() {
            addCriterion("emp_cname is not null");
            return (Criteria) this;
        }

        public Criteria andEmpCnameEqualTo(String value) {
            addCriterion("emp_cname =", value, "empCname");
            return (Criteria) this;
        }

        public Criteria andEmpCnameNotEqualTo(String value) {
            addCriterion("emp_cname <>", value, "empCname");
            return (Criteria) this;
        }

        public Criteria andEmpCnameGreaterThan(String value) {
            addCriterion("emp_cname >", value, "empCname");
            return (Criteria) this;
        }

        public Criteria andEmpCnameGreaterThanOrEqualTo(String value) {
            addCriterion("emp_cname >=", value, "empCname");
            return (Criteria) this;
        }

        public Criteria andEmpCnameLessThan(String value) {
            addCriterion("emp_cname <", value, "empCname");
            return (Criteria) this;
        }

        public Criteria andEmpCnameLessThanOrEqualTo(String value) {
            addCriterion("emp_cname <=", value, "empCname");
            return (Criteria) this;
        }

        public Criteria andEmpCnameLike(String value) {
            addCriterion("emp_cname like", value, "empCname");
            return (Criteria) this;
        }

        public Criteria andEmpCnameNotLike(String value) {
            addCriterion("emp_cname not like", value, "empCname");
            return (Criteria) this;
        }

        public Criteria andEmpCnameIn(List<String> values) {
            addCriterion("emp_cname in", values, "empCname");
            return (Criteria) this;
        }

        public Criteria andEmpCnameNotIn(List<String> values) {
            addCriterion("emp_cname not in", values, "empCname");
            return (Criteria) this;
        }

        public Criteria andEmpCnameBetween(String value1, String value2) {
            addCriterion("emp_cname between", value1, value2, "empCname");
            return (Criteria) this;
        }

        public Criteria andEmpCnameNotBetween(String value1, String value2) {
            addCriterion("emp_cname not between", value1, value2, "empCname");
            return (Criteria) this;
        }

        public Criteria andEmpFnameIsNull() {
            addCriterion("emp_fname is null");
            return (Criteria) this;
        }

        public Criteria andEmpFnameIsNotNull() {
            addCriterion("emp_fname is not null");
            return (Criteria) this;
        }

        public Criteria andEmpFnameEqualTo(String value) {
            addCriterion("emp_fname =", value, "empFname");
            return (Criteria) this;
        }

        public Criteria andEmpFnameNotEqualTo(String value) {
            addCriterion("emp_fname <>", value, "empFname");
            return (Criteria) this;
        }

        public Criteria andEmpFnameGreaterThan(String value) {
            addCriterion("emp_fname >", value, "empFname");
            return (Criteria) this;
        }

        public Criteria andEmpFnameGreaterThanOrEqualTo(String value) {
            addCriterion("emp_fname >=", value, "empFname");
            return (Criteria) this;
        }

        public Criteria andEmpFnameLessThan(String value) {
            addCriterion("emp_fname <", value, "empFname");
            return (Criteria) this;
        }

        public Criteria andEmpFnameLessThanOrEqualTo(String value) {
            addCriterion("emp_fname <=", value, "empFname");
            return (Criteria) this;
        }

        public Criteria andEmpFnameLike(String value) {
            addCriterion("emp_fname like", value, "empFname");
            return (Criteria) this;
        }

        public Criteria andEmpFnameNotLike(String value) {
            addCriterion("emp_fname not like", value, "empFname");
            return (Criteria) this;
        }

        public Criteria andEmpFnameIn(List<String> values) {
            addCriterion("emp_fname in", values, "empFname");
            return (Criteria) this;
        }

        public Criteria andEmpFnameNotIn(List<String> values) {
            addCriterion("emp_fname not in", values, "empFname");
            return (Criteria) this;
        }

        public Criteria andEmpFnameBetween(String value1, String value2) {
            addCriterion("emp_fname between", value1, value2, "empFname");
            return (Criteria) this;
        }

        public Criteria andEmpFnameNotBetween(String value1, String value2) {
            addCriterion("emp_fname not between", value1, value2, "empFname");
            return (Criteria) this;
        }

        public Criteria andEmpLnameIsNull() {
            addCriterion("emp_lname is null");
            return (Criteria) this;
        }

        public Criteria andEmpLnameIsNotNull() {
            addCriterion("emp_lname is not null");
            return (Criteria) this;
        }

        public Criteria andEmpLnameEqualTo(String value) {
            addCriterion("emp_lname =", value, "empLname");
            return (Criteria) this;
        }

        public Criteria andEmpLnameNotEqualTo(String value) {
            addCriterion("emp_lname <>", value, "empLname");
            return (Criteria) this;
        }

        public Criteria andEmpLnameGreaterThan(String value) {
            addCriterion("emp_lname >", value, "empLname");
            return (Criteria) this;
        }

        public Criteria andEmpLnameGreaterThanOrEqualTo(String value) {
            addCriterion("emp_lname >=", value, "empLname");
            return (Criteria) this;
        }

        public Criteria andEmpLnameLessThan(String value) {
            addCriterion("emp_lname <", value, "empLname");
            return (Criteria) this;
        }

        public Criteria andEmpLnameLessThanOrEqualTo(String value) {
            addCriterion("emp_lname <=", value, "empLname");
            return (Criteria) this;
        }

        public Criteria andEmpLnameLike(String value) {
            addCriterion("emp_lname like", value, "empLname");
            return (Criteria) this;
        }

        public Criteria andEmpLnameNotLike(String value) {
            addCriterion("emp_lname not like", value, "empLname");
            return (Criteria) this;
        }

        public Criteria andEmpLnameIn(List<String> values) {
            addCriterion("emp_lname in", values, "empLname");
            return (Criteria) this;
        }

        public Criteria andEmpLnameNotIn(List<String> values) {
            addCriterion("emp_lname not in", values, "empLname");
            return (Criteria) this;
        }

        public Criteria andEmpLnameBetween(String value1, String value2) {
            addCriterion("emp_lname between", value1, value2, "empLname");
            return (Criteria) this;
        }

        public Criteria andEmpLnameNotBetween(String value1, String value2) {
            addCriterion("emp_lname not between", value1, value2, "empLname");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnoIsNull() {
            addCriterion("emp_deptno is null");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnoIsNotNull() {
            addCriterion("emp_deptno is not null");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnoEqualTo(String value) {
            addCriterion("emp_deptno =", value, "empDeptno");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnoNotEqualTo(String value) {
            addCriterion("emp_deptno <>", value, "empDeptno");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnoGreaterThan(String value) {
            addCriterion("emp_deptno >", value, "empDeptno");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnoGreaterThanOrEqualTo(String value) {
            addCriterion("emp_deptno >=", value, "empDeptno");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnoLessThan(String value) {
            addCriterion("emp_deptno <", value, "empDeptno");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnoLessThanOrEqualTo(String value) {
            addCriterion("emp_deptno <=", value, "empDeptno");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnoLike(String value) {
            addCriterion("emp_deptno like", value, "empDeptno");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnoNotLike(String value) {
            addCriterion("emp_deptno not like", value, "empDeptno");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnoIn(List<String> values) {
            addCriterion("emp_deptno in", values, "empDeptno");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnoNotIn(List<String> values) {
            addCriterion("emp_deptno not in", values, "empDeptno");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnoBetween(String value1, String value2) {
            addCriterion("emp_deptno between", value1, value2, "empDeptno");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnoNotBetween(String value1, String value2) {
            addCriterion("emp_deptno not between", value1, value2, "empDeptno");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnameIsNull() {
            addCriterion("emp_deptname is null");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnameIsNotNull() {
            addCriterion("emp_deptname is not null");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnameEqualTo(String value) {
            addCriterion("emp_deptname =", value, "empDeptname");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnameNotEqualTo(String value) {
            addCriterion("emp_deptname <>", value, "empDeptname");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnameGreaterThan(String value) {
            addCriterion("emp_deptname >", value, "empDeptname");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnameGreaterThanOrEqualTo(String value) {
            addCriterion("emp_deptname >=", value, "empDeptname");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnameLessThan(String value) {
            addCriterion("emp_deptname <", value, "empDeptname");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnameLessThanOrEqualTo(String value) {
            addCriterion("emp_deptname <=", value, "empDeptname");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnameLike(String value) {
            addCriterion("emp_deptname like", value, "empDeptname");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnameNotLike(String value) {
            addCriterion("emp_deptname not like", value, "empDeptname");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnameIn(List<String> values) {
            addCriterion("emp_deptname in", values, "empDeptname");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnameNotIn(List<String> values) {
            addCriterion("emp_deptname not in", values, "empDeptname");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnameBetween(String value1, String value2) {
            addCriterion("emp_deptname between", value1, value2, "empDeptname");
            return (Criteria) this;
        }

        public Criteria andEmpDeptnameNotBetween(String value1, String value2) {
            addCriterion("emp_deptname not between", value1, value2, "empDeptname");
            return (Criteria) this;
        }

        public Criteria andEmpRateIsNull() {
            addCriterion("emp_rate is null");
            return (Criteria) this;
        }

        public Criteria andEmpRateIsNotNull() {
            addCriterion("emp_rate is not null");
            return (Criteria) this;
        }

        public Criteria andEmpRateEqualTo(BigDecimal value) {
            addCriterion("emp_rate =", value, "empRate");
            return (Criteria) this;
        }

        public Criteria andEmpRateNotEqualTo(BigDecimal value) {
            addCriterion("emp_rate <>", value, "empRate");
            return (Criteria) this;
        }

        public Criteria andEmpRateGreaterThan(BigDecimal value) {
            addCriterion("emp_rate >", value, "empRate");
            return (Criteria) this;
        }

        public Criteria andEmpRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("emp_rate >=", value, "empRate");
            return (Criteria) this;
        }

        public Criteria andEmpRateLessThan(BigDecimal value) {
            addCriterion("emp_rate <", value, "empRate");
            return (Criteria) this;
        }

        public Criteria andEmpRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("emp_rate <=", value, "empRate");
            return (Criteria) this;
        }

        public Criteria andEmpRateIn(List<BigDecimal> values) {
            addCriterion("emp_rate in", values, "empRate");
            return (Criteria) this;
        }

        public Criteria andEmpRateNotIn(List<BigDecimal> values) {
            addCriterion("emp_rate not in", values, "empRate");
            return (Criteria) this;
        }

        public Criteria andEmpRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("emp_rate between", value1, value2, "empRate");
            return (Criteria) this;
        }

        public Criteria andEmpRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("emp_rate not between", value1, value2, "empRate");
            return (Criteria) this;
        }

        public Criteria andPrizeFlagIsNull() {
            addCriterion("prize_flag is null");
            return (Criteria) this;
        }

        public Criteria andPrizeFlagIsNotNull() {
            addCriterion("prize_flag is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeFlagEqualTo(BigDecimal value) {
            addCriterion("prize_flag =", value, "prizeFlag");
            return (Criteria) this;
        }

        public Criteria andPrizeFlagNotEqualTo(BigDecimal value) {
            addCriterion("prize_flag <>", value, "prizeFlag");
            return (Criteria) this;
        }

        public Criteria andPrizeFlagGreaterThan(BigDecimal value) {
            addCriterion("prize_flag >", value, "prizeFlag");
            return (Criteria) this;
        }

        public Criteria andPrizeFlagGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("prize_flag >=", value, "prizeFlag");
            return (Criteria) this;
        }

        public Criteria andPrizeFlagLessThan(BigDecimal value) {
            addCriterion("prize_flag <", value, "prizeFlag");
            return (Criteria) this;
        }

        public Criteria andPrizeFlagLessThanOrEqualTo(BigDecimal value) {
            addCriterion("prize_flag <=", value, "prizeFlag");
            return (Criteria) this;
        }

        public Criteria andPrizeFlagIn(List<BigDecimal> values) {
            addCriterion("prize_flag in", values, "prizeFlag");
            return (Criteria) this;
        }

        public Criteria andPrizeFlagNotIn(List<BigDecimal> values) {
            addCriterion("prize_flag not in", values, "prizeFlag");
            return (Criteria) this;
        }

        public Criteria andPrizeFlagBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("prize_flag between", value1, value2, "prizeFlag");
            return (Criteria) this;
        }

        public Criteria andPrizeFlagNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("prize_flag not between", value1, value2, "prizeFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_emp_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}