package com.wistronits.wistlotto.model.tables;

import java.io.Serializable;
import java.math.BigDecimal;

public class TEmpInfo extends TEmpInfoKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp_info.emp_cname
     *
     * @mbg.generated
     */
    private String empCname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp_info.emp_fname
     *
     * @mbg.generated
     */
    private String empFname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp_info.emp_lname
     *
     * @mbg.generated
     */
    private String empLname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp_info.emp_deptno
     *
     * @mbg.generated
     */
    private String empDeptno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp_info.emp_deptname
     *
     * @mbg.generated
     */
    private String empDeptname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp_info.emp_rate
     *
     * @mbg.generated
     */
    private BigDecimal empRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp_info.prize_flag
     *
     * @mbg.generated
     */
    private BigDecimal prizeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp_info.emp_cname
     *
     * @return the value of t_emp_info.emp_cname
     *
     * @mbg.generated
     */
    public String getEmpCname() {
        return empCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp_info.emp_cname
     *
     * @param empCname the value for t_emp_info.emp_cname
     *
     * @mbg.generated
     */
    public void setEmpCname(String empCname) {
        this.empCname = empCname == null ? null : empCname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp_info.emp_fname
     *
     * @return the value of t_emp_info.emp_fname
     *
     * @mbg.generated
     */
    public String getEmpFname() {
        return empFname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp_info.emp_fname
     *
     * @param empFname the value for t_emp_info.emp_fname
     *
     * @mbg.generated
     */
    public void setEmpFname(String empFname) {
        this.empFname = empFname == null ? null : empFname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp_info.emp_lname
     *
     * @return the value of t_emp_info.emp_lname
     *
     * @mbg.generated
     */
    public String getEmpLname() {
        return empLname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp_info.emp_lname
     *
     * @param empLname the value for t_emp_info.emp_lname
     *
     * @mbg.generated
     */
    public void setEmpLname(String empLname) {
        this.empLname = empLname == null ? null : empLname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp_info.emp_deptno
     *
     * @return the value of t_emp_info.emp_deptno
     *
     * @mbg.generated
     */
    public String getEmpDeptno() {
        return empDeptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp_info.emp_deptno
     *
     * @param empDeptno the value for t_emp_info.emp_deptno
     *
     * @mbg.generated
     */
    public void setEmpDeptno(String empDeptno) {
        this.empDeptno = empDeptno == null ? null : empDeptno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp_info.emp_deptname
     *
     * @return the value of t_emp_info.emp_deptname
     *
     * @mbg.generated
     */
    public String getEmpDeptname() {
        return empDeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp_info.emp_deptname
     *
     * @param empDeptname the value for t_emp_info.emp_deptname
     *
     * @mbg.generated
     */
    public void setEmpDeptname(String empDeptname) {
        this.empDeptname = empDeptname == null ? null : empDeptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp_info.emp_rate
     *
     * @return the value of t_emp_info.emp_rate
     *
     * @mbg.generated
     */
    public BigDecimal getEmpRate() {
        return empRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp_info.emp_rate
     *
     * @param empRate the value for t_emp_info.emp_rate
     *
     * @mbg.generated
     */
    public void setEmpRate(BigDecimal empRate) {
        this.empRate = empRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp_info.prize_flag
     *
     * @return the value of t_emp_info.prize_flag
     *
     * @mbg.generated
     */
    public BigDecimal getPrizeFlag() {
        return prizeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp_info.prize_flag
     *
     * @param prizeFlag the value for t_emp_info.prize_flag
     *
     * @mbg.generated
     */
    public void setPrizeFlag(BigDecimal prizeFlag) {
        this.prizeFlag = prizeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TEmpInfo other = (TEmpInfo) that;
        return (this.getEmpId() == null ? other.getEmpId() == null : this.getEmpId().equals(other.getEmpId()))
            && (this.getEmpCname() == null ? other.getEmpCname() == null : this.getEmpCname().equals(other.getEmpCname()))
            && (this.getEmpFname() == null ? other.getEmpFname() == null : this.getEmpFname().equals(other.getEmpFname()))
            && (this.getEmpLname() == null ? other.getEmpLname() == null : this.getEmpLname().equals(other.getEmpLname()))
            && (this.getEmpDeptno() == null ? other.getEmpDeptno() == null : this.getEmpDeptno().equals(other.getEmpDeptno()))
            && (this.getEmpDeptname() == null ? other.getEmpDeptname() == null : this.getEmpDeptname().equals(other.getEmpDeptname()))
            && (this.getEmpRate() == null ? other.getEmpRate() == null : this.getEmpRate().equals(other.getEmpRate()))
            && (this.getPrizeFlag() == null ? other.getPrizeFlag() == null : this.getPrizeFlag().equals(other.getPrizeFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEmpId() == null) ? 0 : getEmpId().hashCode());
        result = prime * result + ((getEmpCname() == null) ? 0 : getEmpCname().hashCode());
        result = prime * result + ((getEmpFname() == null) ? 0 : getEmpFname().hashCode());
        result = prime * result + ((getEmpLname() == null) ? 0 : getEmpLname().hashCode());
        result = prime * result + ((getEmpDeptno() == null) ? 0 : getEmpDeptno().hashCode());
        result = prime * result + ((getEmpDeptname() == null) ? 0 : getEmpDeptname().hashCode());
        result = prime * result + ((getEmpRate() == null) ? 0 : getEmpRate().hashCode());
        result = prime * result + ((getPrizeFlag() == null) ? 0 : getPrizeFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", empCname=").append(empCname);
        sb.append(", empFname=").append(empFname);
        sb.append(", empLname=").append(empLname);
        sb.append(", empDeptno=").append(empDeptno);
        sb.append(", empDeptname=").append(empDeptname);
        sb.append(", empRate=").append(empRate);
        sb.append(", prizeFlag=").append(prizeFlag);
        sb.append("]");
        return sb.toString();
    }
}