package com.wistronits.wistlotto.model.tables;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TEmpInfoCriteria {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	public TEmpInfoCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andEmpIdIsNull() {
			addCriterion("emp_id is null");
			return (Criteria) this;
		}

		public Criteria andEmpIdIsNotNull() {
			addCriterion("emp_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmpIdEqualTo(String value) {
			addCriterion("emp_id =", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotEqualTo(String value) {
			addCriterion("emp_id <>", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdGreaterThan(String value) {
			addCriterion("emp_id >", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdGreaterThanOrEqualTo(String value) {
			addCriterion("emp_id >=", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdLessThan(String value) {
			addCriterion("emp_id <", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdLessThanOrEqualTo(String value) {
			addCriterion("emp_id <=", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdLike(String value) {
			addCriterion("emp_id like", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotLike(String value) {
			addCriterion("emp_id not like", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdIn(List<String> values) {
			addCriterion("emp_id in", values, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotIn(List<String> values) {
			addCriterion("emp_id not in", values, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdBetween(String value1, String value2) {
			addCriterion("emp_id between", value1, value2, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotBetween(String value1, String value2) {
			addCriterion("emp_id not between", value1, value2, "empId");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNull() {
			addCriterion("group_id is null");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNotNull() {
			addCriterion("group_id is not null");
			return (Criteria) this;
		}

		public Criteria andGroupIdEqualTo(String value) {
			addCriterion("group_id =", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotEqualTo(String value) {
			addCriterion("group_id <>", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThan(String value) {
			addCriterion("group_id >", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThanOrEqualTo(String value) {
			addCriterion("group_id >=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThan(String value) {
			addCriterion("group_id <", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThanOrEqualTo(String value) {
			addCriterion("group_id <=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLike(String value) {
			addCriterion("group_id like", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotLike(String value) {
			addCriterion("group_id not like", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdIn(List<String> values) {
			addCriterion("group_id in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotIn(List<String> values) {
			addCriterion("group_id not in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdBetween(String value1, String value2) {
			addCriterion("group_id between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotBetween(String value1, String value2) {
			addCriterion("group_id not between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andEmpNameIsNull() {
			addCriterion("emp_name is null");
			return (Criteria) this;
		}

		public Criteria andEmpNameIsNotNull() {
			addCriterion("emp_name is not null");
			return (Criteria) this;
		}

		public Criteria andEmpNameEqualTo(String value) {
			addCriterion("emp_name =", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameNotEqualTo(String value) {
			addCriterion("emp_name <>", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameGreaterThan(String value) {
			addCriterion("emp_name >", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameGreaterThanOrEqualTo(String value) {
			addCriterion("emp_name >=", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameLessThan(String value) {
			addCriterion("emp_name <", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameLessThanOrEqualTo(String value) {
			addCriterion("emp_name <=", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameLike(String value) {
			addCriterion("emp_name like", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameNotLike(String value) {
			addCriterion("emp_name not like", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameIn(List<String> values) {
			addCriterion("emp_name in", values, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameNotIn(List<String> values) {
			addCriterion("emp_name not in", values, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameBetween(String value1, String value2) {
			addCriterion("emp_name between", value1, value2, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameNotBetween(String value1, String value2) {
			addCriterion("emp_name not between", value1, value2, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpSexIsNull() {
			addCriterion("emp_sex is null");
			return (Criteria) this;
		}

		public Criteria andEmpSexIsNotNull() {
			addCriterion("emp_sex is not null");
			return (Criteria) this;
		}

		public Criteria andEmpSexEqualTo(String value) {
			addCriterion("emp_sex =", value, "empSex");
			return (Criteria) this;
		}

		public Criteria andEmpSexNotEqualTo(String value) {
			addCriterion("emp_sex <>", value, "empSex");
			return (Criteria) this;
		}

		public Criteria andEmpSexGreaterThan(String value) {
			addCriterion("emp_sex >", value, "empSex");
			return (Criteria) this;
		}

		public Criteria andEmpSexGreaterThanOrEqualTo(String value) {
			addCriterion("emp_sex >=", value, "empSex");
			return (Criteria) this;
		}

		public Criteria andEmpSexLessThan(String value) {
			addCriterion("emp_sex <", value, "empSex");
			return (Criteria) this;
		}

		public Criteria andEmpSexLessThanOrEqualTo(String value) {
			addCriterion("emp_sex <=", value, "empSex");
			return (Criteria) this;
		}

		public Criteria andEmpSexLike(String value) {
			addCriterion("emp_sex like", value, "empSex");
			return (Criteria) this;
		}

		public Criteria andEmpSexNotLike(String value) {
			addCriterion("emp_sex not like", value, "empSex");
			return (Criteria) this;
		}

		public Criteria andEmpSexIn(List<String> values) {
			addCriterion("emp_sex in", values, "empSex");
			return (Criteria) this;
		}

		public Criteria andEmpSexNotIn(List<String> values) {
			addCriterion("emp_sex not in", values, "empSex");
			return (Criteria) this;
		}

		public Criteria andEmpSexBetween(String value1, String value2) {
			addCriterion("emp_sex between", value1, value2, "empSex");
			return (Criteria) this;
		}

		public Criteria andEmpSexNotBetween(String value1, String value2) {
			addCriterion("emp_sex not between", value1, value2, "empSex");
			return (Criteria) this;
		}

		public Criteria andEmpDateIsNull() {
			addCriterion("emp_date is null");
			return (Criteria) this;
		}

		public Criteria andEmpDateIsNotNull() {
			addCriterion("emp_date is not null");
			return (Criteria) this;
		}

		public Criteria andEmpDateEqualTo(String value) {
			addCriterion("emp_date =", value, "empDate");
			return (Criteria) this;
		}

		public Criteria andEmpDateNotEqualTo(String value) {
			addCriterion("emp_date <>", value, "empDate");
			return (Criteria) this;
		}

		public Criteria andEmpDateGreaterThan(String value) {
			addCriterion("emp_date >", value, "empDate");
			return (Criteria) this;
		}

		public Criteria andEmpDateGreaterThanOrEqualTo(String value) {
			addCriterion("emp_date >=", value, "empDate");
			return (Criteria) this;
		}

		public Criteria andEmpDateLessThan(String value) {
			addCriterion("emp_date <", value, "empDate");
			return (Criteria) this;
		}

		public Criteria andEmpDateLessThanOrEqualTo(String value) {
			addCriterion("emp_date <=", value, "empDate");
			return (Criteria) this;
		}

		public Criteria andEmpDateLike(String value) {
			addCriterion("emp_date like", value, "empDate");
			return (Criteria) this;
		}

		public Criteria andEmpDateNotLike(String value) {
			addCriterion("emp_date not like", value, "empDate");
			return (Criteria) this;
		}

		public Criteria andEmpDateIn(List<String> values) {
			addCriterion("emp_date in", values, "empDate");
			return (Criteria) this;
		}

		public Criteria andEmpDateNotIn(List<String> values) {
			addCriterion("emp_date not in", values, "empDate");
			return (Criteria) this;
		}

		public Criteria andEmpDateBetween(String value1, String value2) {
			addCriterion("emp_date between", value1, value2, "empDate");
			return (Criteria) this;
		}

		public Criteria andEmpDateNotBetween(String value1, String value2) {
			addCriterion("emp_date not between", value1, value2, "empDate");
			return (Criteria) this;
		}

		public Criteria andDeptIdIsNull() {
			addCriterion("dept_id is null");
			return (Criteria) this;
		}

		public Criteria andDeptIdIsNotNull() {
			addCriterion("dept_id is not null");
			return (Criteria) this;
		}

		public Criteria andDeptIdEqualTo(String value) {
			addCriterion("dept_id =", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdNotEqualTo(String value) {
			addCriterion("dept_id <>", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdGreaterThan(String value) {
			addCriterion("dept_id >", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdGreaterThanOrEqualTo(String value) {
			addCriterion("dept_id >=", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdLessThan(String value) {
			addCriterion("dept_id <", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdLessThanOrEqualTo(String value) {
			addCriterion("dept_id <=", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdLike(String value) {
			addCriterion("dept_id like", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdNotLike(String value) {
			addCriterion("dept_id not like", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdIn(List<String> values) {
			addCriterion("dept_id in", values, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdNotIn(List<String> values) {
			addCriterion("dept_id not in", values, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdBetween(String value1, String value2) {
			addCriterion("dept_id between", value1, value2, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdNotBetween(String value1, String value2) {
			addCriterion("dept_id not between", value1, value2, "deptId");
			return (Criteria) this;
		}

		public Criteria andEmpRateIsNull() {
			addCriterion("emp_rate is null");
			return (Criteria) this;
		}

		public Criteria andEmpRateIsNotNull() {
			addCriterion("emp_rate is not null");
			return (Criteria) this;
		}

		public Criteria andEmpRateEqualTo(BigDecimal value) {
			addCriterion("emp_rate =", value, "empRate");
			return (Criteria) this;
		}

		public Criteria andEmpRateNotEqualTo(BigDecimal value) {
			addCriterion("emp_rate <>", value, "empRate");
			return (Criteria) this;
		}

		public Criteria andEmpRateGreaterThan(BigDecimal value) {
			addCriterion("emp_rate >", value, "empRate");
			return (Criteria) this;
		}

		public Criteria andEmpRateGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("emp_rate >=", value, "empRate");
			return (Criteria) this;
		}

		public Criteria andEmpRateLessThan(BigDecimal value) {
			addCriterion("emp_rate <", value, "empRate");
			return (Criteria) this;
		}

		public Criteria andEmpRateLessThanOrEqualTo(BigDecimal value) {
			addCriterion("emp_rate <=", value, "empRate");
			return (Criteria) this;
		}

		public Criteria andEmpRateIn(List<BigDecimal> values) {
			addCriterion("emp_rate in", values, "empRate");
			return (Criteria) this;
		}

		public Criteria andEmpRateNotIn(List<BigDecimal> values) {
			addCriterion("emp_rate not in", values, "empRate");
			return (Criteria) this;
		}

		public Criteria andEmpRateBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("emp_rate between", value1, value2, "empRate");
			return (Criteria) this;
		}

		public Criteria andEmpRateNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("emp_rate not between", value1, value2, "empRate");
			return (Criteria) this;
		}

		public Criteria andPrizeFlagIsNull() {
			addCriterion("prize_flag is null");
			return (Criteria) this;
		}

		public Criteria andPrizeFlagIsNotNull() {
			addCriterion("prize_flag is not null");
			return (Criteria) this;
		}

		public Criteria andPrizeFlagEqualTo(String value) {
			addCriterion("prize_flag =", value, "prizeFlag");
			return (Criteria) this;
		}

		public Criteria andPrizeFlagNotEqualTo(String value) {
			addCriterion("prize_flag <>", value, "prizeFlag");
			return (Criteria) this;
		}

		public Criteria andPrizeFlagGreaterThan(String value) {
			addCriterion("prize_flag >", value, "prizeFlag");
			return (Criteria) this;
		}

		public Criteria andPrizeFlagGreaterThanOrEqualTo(String value) {
			addCriterion("prize_flag >=", value, "prizeFlag");
			return (Criteria) this;
		}

		public Criteria andPrizeFlagLessThan(String value) {
			addCriterion("prize_flag <", value, "prizeFlag");
			return (Criteria) this;
		}

		public Criteria andPrizeFlagLessThanOrEqualTo(String value) {
			addCriterion("prize_flag <=", value, "prizeFlag");
			return (Criteria) this;
		}

		public Criteria andPrizeFlagLike(String value) {
			addCriterion("prize_flag like", value, "prizeFlag");
			return (Criteria) this;
		}

		public Criteria andPrizeFlagNotLike(String value) {
			addCriterion("prize_flag not like", value, "prizeFlag");
			return (Criteria) this;
		}

		public Criteria andPrizeFlagIn(List<String> values) {
			addCriterion("prize_flag in", values, "prizeFlag");
			return (Criteria) this;
		}

		public Criteria andPrizeFlagNotIn(List<String> values) {
			addCriterion("prize_flag not in", values, "prizeFlag");
			return (Criteria) this;
		}

		public Criteria andPrizeFlagBetween(String value1, String value2) {
			addCriterion("prize_flag between", value1, value2, "prizeFlag");
			return (Criteria) this;
		}

		public Criteria andPrizeFlagNotBetween(String value1, String value2) {
			addCriterion("prize_flag not between", value1, value2, "prizeFlag");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table t_emp_info
	 * 
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table t_emp_info
	 *
	 * @mbg.generated do_not_delete_during_merge
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}
}