package com.wistronits.wistlotto.model.tables;

import java.io.Serializable;
import java.math.BigDecimal;

public class TPrizeInfo extends TPrizeInfoKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_prize_info.prize_name
	 * @mbg.generated
	 */
	private String prizeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_prize_info.prize_desc
	 * @mbg.generated
	 */
	private String prizeDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_prize_info.prize_order
	 * @mbg.generated
	 */
	private BigDecimal prizeOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_prize_info.prize_number
	 * @mbg.generated
	 */
	private BigDecimal prizeNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_prize_info.prize_winner
	 * @mbg.generated
	 */
	private BigDecimal prizeWinner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_prize_info.dept_id
	 * @mbg.generated
	 */
	private String deptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_prize_info.prize_multi
	 * @mbg.generated
	 */
	private BigDecimal prizeMulti;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_prize_info.prize_status
	 * @mbg.generated
	 */
	private BigDecimal prizeStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_prize_info.prize_person
	 * @mbg.generated
	 */
	private BigDecimal prizePerson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_prize_info
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_prize_info.prize_name
	 * @return  the value of t_prize_info.prize_name
	 * @mbg.generated
	 */
	public String getPrizeName() {
		return prizeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_prize_info.prize_name
	 * @param prizeName  the value for t_prize_info.prize_name
	 * @mbg.generated
	 */
	public void setPrizeName(String prizeName) {
		this.prizeName = prizeName == null ? null : prizeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_prize_info.prize_desc
	 * @return  the value of t_prize_info.prize_desc
	 * @mbg.generated
	 */
	public String getPrizeDesc() {
		return prizeDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_prize_info.prize_desc
	 * @param prizeDesc  the value for t_prize_info.prize_desc
	 * @mbg.generated
	 */
	public void setPrizeDesc(String prizeDesc) {
		this.prizeDesc = prizeDesc == null ? null : prizeDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_prize_info.prize_order
	 * @return  the value of t_prize_info.prize_order
	 * @mbg.generated
	 */
	public BigDecimal getPrizeOrder() {
		return prizeOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_prize_info.prize_order
	 * @param prizeOrder  the value for t_prize_info.prize_order
	 * @mbg.generated
	 */
	public void setPrizeOrder(BigDecimal prizeOrder) {
		this.prizeOrder = prizeOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_prize_info.prize_number
	 * @return  the value of t_prize_info.prize_number
	 * @mbg.generated
	 */
	public BigDecimal getPrizeNumber() {
		return prizeNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_prize_info.prize_number
	 * @param prizeNumber  the value for t_prize_info.prize_number
	 * @mbg.generated
	 */
	public void setPrizeNumber(BigDecimal prizeNumber) {
		this.prizeNumber = prizeNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_prize_info.prize_winner
	 * @return  the value of t_prize_info.prize_winner
	 * @mbg.generated
	 */
	public BigDecimal getPrizeWinner() {
		return prizeWinner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_prize_info.prize_winner
	 * @param prizeWinner  the value for t_prize_info.prize_winner
	 * @mbg.generated
	 */
	public void setPrizeWinner(BigDecimal prizeWinner) {
		this.prizeWinner = prizeWinner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_prize_info.dept_id
	 * @return  the value of t_prize_info.dept_id
	 * @mbg.generated
	 */
	public String getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_prize_info.dept_id
	 * @param deptId  the value for t_prize_info.dept_id
	 * @mbg.generated
	 */
	public void setDeptId(String deptId) {
		this.deptId = deptId == null ? null : deptId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_prize_info.prize_multi
	 * @return  the value of t_prize_info.prize_multi
	 * @mbg.generated
	 */
	public BigDecimal getPrizeMulti() {
		return prizeMulti;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_prize_info.prize_multi
	 * @param prizeMulti  the value for t_prize_info.prize_multi
	 * @mbg.generated
	 */
	public void setPrizeMulti(BigDecimal prizeMulti) {
		this.prizeMulti = prizeMulti;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_prize_info.prize_status
	 * @return  the value of t_prize_info.prize_status
	 * @mbg.generated
	 */
	public BigDecimal getPrizeStatus() {
		return prizeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_prize_info.prize_status
	 * @param prizeStatus  the value for t_prize_info.prize_status
	 * @mbg.generated
	 */
	public void setPrizeStatus(BigDecimal prizeStatus) {
		this.prizeStatus = prizeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_prize_info.prize_person
	 * @return  the value of t_prize_info.prize_person
	 * @mbg.generated
	 */
	public BigDecimal getPrizePerson() {
		return prizePerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_prize_info.prize_person
	 * @param prizePerson  the value for t_prize_info.prize_person
	 * @mbg.generated
	 */
	public void setPrizePerson(BigDecimal prizePerson) {
		this.prizePerson = prizePerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_info
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		TPrizeInfo other = (TPrizeInfo) that;
		return (this.getPrizeId() == null ? other.getPrizeId() == null : this.getPrizeId().equals(other.getPrizeId()))
				&& (this.getPrizeName() == null ? other.getPrizeName() == null
						: this.getPrizeName().equals(other.getPrizeName()))
				&& (this.getPrizeDesc() == null ? other.getPrizeDesc() == null
						: this.getPrizeDesc().equals(other.getPrizeDesc()))
				&& (this.getPrizeOrder() == null ? other.getPrizeOrder() == null
						: this.getPrizeOrder().equals(other.getPrizeOrder()))
				&& (this.getPrizeNumber() == null ? other.getPrizeNumber() == null
						: this.getPrizeNumber().equals(other.getPrizeNumber()))
				&& (this.getPrizeWinner() == null ? other.getPrizeWinner() == null
						: this.getPrizeWinner().equals(other.getPrizeWinner()))
				&& (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
				&& (this.getPrizeMulti() == null ? other.getPrizeMulti() == null
						: this.getPrizeMulti().equals(other.getPrizeMulti()))
				&& (this.getPrizeStatus() == null ? other.getPrizeStatus() == null
						: this.getPrizeStatus().equals(other.getPrizeStatus()))
				&& (this.getPrizePerson() == null ? other.getPrizePerson() == null
						: this.getPrizePerson().equals(other.getPrizePerson()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_info
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getPrizeId() == null) ? 0 : getPrizeId().hashCode());
		result = prime * result + ((getPrizeName() == null) ? 0 : getPrizeName().hashCode());
		result = prime * result + ((getPrizeDesc() == null) ? 0 : getPrizeDesc().hashCode());
		result = prime * result + ((getPrizeOrder() == null) ? 0 : getPrizeOrder().hashCode());
		result = prime * result + ((getPrizeNumber() == null) ? 0 : getPrizeNumber().hashCode());
		result = prime * result + ((getPrizeWinner() == null) ? 0 : getPrizeWinner().hashCode());
		result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
		result = prime * result + ((getPrizeMulti() == null) ? 0 : getPrizeMulti().hashCode());
		result = prime * result + ((getPrizeStatus() == null) ? 0 : getPrizeStatus().hashCode());
		result = prime * result + ((getPrizePerson() == null) ? 0 : getPrizePerson().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_info
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", prizeName=").append(prizeName);
		sb.append(", prizeDesc=").append(prizeDesc);
		sb.append(", prizeOrder=").append(prizeOrder);
		sb.append(", prizeNumber=").append(prizeNumber);
		sb.append(", prizeWinner=").append(prizeWinner);
		sb.append(", deptId=").append(deptId);
		sb.append(", prizeMulti=").append(prizeMulti);
		sb.append(", prizeStatus=").append(prizeStatus);
		sb.append(", prizePerson=").append(prizePerson);
		sb.append("]");
		return sb.toString();
	}
}