package com.wistronits.wistlotto.model.tables;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TPrizeGroupInfoCriteria {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	public TPrizeGroupInfoCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPrizeIdIsNull() {
			addCriterion("prize_id is null");
			return (Criteria) this;
		}

		public Criteria andPrizeIdIsNotNull() {
			addCriterion("prize_id is not null");
			return (Criteria) this;
		}

		public Criteria andPrizeIdEqualTo(String value) {
			addCriterion("prize_id =", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdNotEqualTo(String value) {
			addCriterion("prize_id <>", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdGreaterThan(String value) {
			addCriterion("prize_id >", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdGreaterThanOrEqualTo(String value) {
			addCriterion("prize_id >=", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdLessThan(String value) {
			addCriterion("prize_id <", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdLessThanOrEqualTo(String value) {
			addCriterion("prize_id <=", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdLike(String value) {
			addCriterion("prize_id like", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdNotLike(String value) {
			addCriterion("prize_id not like", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdIn(List<String> values) {
			addCriterion("prize_id in", values, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdNotIn(List<String> values) {
			addCriterion("prize_id not in", values, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdBetween(String value1, String value2) {
			addCriterion("prize_id between", value1, value2, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdNotBetween(String value1, String value2) {
			addCriterion("prize_id not between", value1, value2, "prizeId");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNull() {
			addCriterion("group_id is null");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNotNull() {
			addCriterion("group_id is not null");
			return (Criteria) this;
		}

		public Criteria andGroupIdEqualTo(String value) {
			addCriterion("group_id =", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotEqualTo(String value) {
			addCriterion("group_id <>", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThan(String value) {
			addCriterion("group_id >", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThanOrEqualTo(String value) {
			addCriterion("group_id >=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThan(String value) {
			addCriterion("group_id <", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThanOrEqualTo(String value) {
			addCriterion("group_id <=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLike(String value) {
			addCriterion("group_id like", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotLike(String value) {
			addCriterion("group_id not like", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdIn(List<String> values) {
			addCriterion("group_id in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotIn(List<String> values) {
			addCriterion("group_id not in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdBetween(String value1, String value2) {
			addCriterion("group_id between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotBetween(String value1, String value2) {
			addCriterion("group_id not between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andPrizeNumberIsNull() {
			addCriterion("prize_number is null");
			return (Criteria) this;
		}

		public Criteria andPrizeNumberIsNotNull() {
			addCriterion("prize_number is not null");
			return (Criteria) this;
		}

		public Criteria andPrizeNumberEqualTo(BigDecimal value) {
			addCriterion("prize_number =", value, "prizeNumber");
			return (Criteria) this;
		}

		public Criteria andPrizeNumberNotEqualTo(BigDecimal value) {
			addCriterion("prize_number <>", value, "prizeNumber");
			return (Criteria) this;
		}

		public Criteria andPrizeNumberGreaterThan(BigDecimal value) {
			addCriterion("prize_number >", value, "prizeNumber");
			return (Criteria) this;
		}

		public Criteria andPrizeNumberGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("prize_number >=", value, "prizeNumber");
			return (Criteria) this;
		}

		public Criteria andPrizeNumberLessThan(BigDecimal value) {
			addCriterion("prize_number <", value, "prizeNumber");
			return (Criteria) this;
		}

		public Criteria andPrizeNumberLessThanOrEqualTo(BigDecimal value) {
			addCriterion("prize_number <=", value, "prizeNumber");
			return (Criteria) this;
		}

		public Criteria andPrizeNumberIn(List<BigDecimal> values) {
			addCriterion("prize_number in", values, "prizeNumber");
			return (Criteria) this;
		}

		public Criteria andPrizeNumberNotIn(List<BigDecimal> values) {
			addCriterion("prize_number not in", values, "prizeNumber");
			return (Criteria) this;
		}

		public Criteria andPrizeNumberBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("prize_number between", value1, value2, "prizeNumber");
			return (Criteria) this;
		}

		public Criteria andPrizeNumberNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("prize_number not between", value1, value2, "prizeNumber");
			return (Criteria) this;
		}

		public Criteria andPrizeWinnerIsNull() {
			addCriterion("prize_winner is null");
			return (Criteria) this;
		}

		public Criteria andPrizeWinnerIsNotNull() {
			addCriterion("prize_winner is not null");
			return (Criteria) this;
		}

		public Criteria andPrizeWinnerEqualTo(BigDecimal value) {
			addCriterion("prize_winner =", value, "prizeWinner");
			return (Criteria) this;
		}

		public Criteria andPrizeWinnerNotEqualTo(BigDecimal value) {
			addCriterion("prize_winner <>", value, "prizeWinner");
			return (Criteria) this;
		}

		public Criteria andPrizeWinnerGreaterThan(BigDecimal value) {
			addCriterion("prize_winner >", value, "prizeWinner");
			return (Criteria) this;
		}

		public Criteria andPrizeWinnerGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("prize_winner >=", value, "prizeWinner");
			return (Criteria) this;
		}

		public Criteria andPrizeWinnerLessThan(BigDecimal value) {
			addCriterion("prize_winner <", value, "prizeWinner");
			return (Criteria) this;
		}

		public Criteria andPrizeWinnerLessThanOrEqualTo(BigDecimal value) {
			addCriterion("prize_winner <=", value, "prizeWinner");
			return (Criteria) this;
		}

		public Criteria andPrizeWinnerIn(List<BigDecimal> values) {
			addCriterion("prize_winner in", values, "prizeWinner");
			return (Criteria) this;
		}

		public Criteria andPrizeWinnerNotIn(List<BigDecimal> values) {
			addCriterion("prize_winner not in", values, "prizeWinner");
			return (Criteria) this;
		}

		public Criteria andPrizeWinnerBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("prize_winner between", value1, value2, "prizeWinner");
			return (Criteria) this;
		}

		public Criteria andPrizeWinnerNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("prize_winner not between", value1, value2, "prizeWinner");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table t_prize_group_info
	 *
	 * @mbg.generated do_not_delete_during_merge
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}
}