package com.wistronits.wistlotto.model.tables;

import java.io.Serializable;

public class TPrizeInfoKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_prize_info.prize_id
	 * 
	 * @mbg.generated
	 */
	private String prizeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table t_prize_info
	 * 
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_prize_info.prize_id
	 * 
	 * @return the value of t_prize_info.prize_id
	 * @mbg.generated
	 */
	public String getPrizeId() {
		return prizeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_prize_info.prize_id
	 * 
	 * @param prizeId the value for t_prize_info.prize_id
	 * @mbg.generated
	 */
	public void setPrizeId(String prizeId) {
		this.prizeId = prizeId == null ? null : prizeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_prize_info
	 * 
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		TPrizeInfoKey other = (TPrizeInfoKey) that;
		return (this.getPrizeId() == null ? other.getPrizeId() == null : this.getPrizeId().equals(other.getPrizeId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_prize_info
	 * 
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getPrizeId() == null) ? 0 : getPrizeId().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_prize_info
	 * 
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", prizeId=").append(prizeId);
		sb.append("]");
		return sb.toString();
	}
}