package com.wistronits.wistlotto.model.tables;

import java.io.Serializable;
import java.math.BigDecimal;

public class TPrizeGroupInfo implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_prize_group_info.prize_id
	 * @mbg.generated
	 */
	private String prizeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_prize_group_info.group_id
	 * @mbg.generated
	 */
	private String groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_prize_group_info.prize_number
	 * @mbg.generated
	 */
	private BigDecimal prizeNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_prize_group_info.prize_winner
	 * @mbg.generated
	 */
	private BigDecimal prizeWinner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_prize_group_info.prize_id
	 * @return  the value of t_prize_group_info.prize_id
	 * @mbg.generated
	 */
	public String getPrizeId() {
		return prizeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_prize_group_info.prize_id
	 * @param prizeId  the value for t_prize_group_info.prize_id
	 * @mbg.generated
	 */
	public void setPrizeId(String prizeId) {
		this.prizeId = prizeId == null ? null : prizeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_prize_group_info.group_id
	 * @return  the value of t_prize_group_info.group_id
	 * @mbg.generated
	 */
	public String getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_prize_group_info.group_id
	 * @param groupId  the value for t_prize_group_info.group_id
	 * @mbg.generated
	 */
	public void setGroupId(String groupId) {
		this.groupId = groupId == null ? null : groupId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_prize_group_info.prize_number
	 * @return  the value of t_prize_group_info.prize_number
	 * @mbg.generated
	 */
	public BigDecimal getPrizeNumber() {
		return prizeNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_prize_group_info.prize_number
	 * @param prizeNumber  the value for t_prize_group_info.prize_number
	 * @mbg.generated
	 */
	public void setPrizeNumber(BigDecimal prizeNumber) {
		this.prizeNumber = prizeNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_prize_group_info.prize_winner
	 * @return  the value of t_prize_group_info.prize_winner
	 * @mbg.generated
	 */
	public BigDecimal getPrizeWinner() {
		return prizeWinner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_prize_group_info.prize_winner
	 * @param prizeWinner  the value for t_prize_group_info.prize_winner
	 * @mbg.generated
	 */
	public void setPrizeWinner(BigDecimal prizeWinner) {
		this.prizeWinner = prizeWinner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		TPrizeGroupInfo other = (TPrizeGroupInfo) that;
		return (this.getPrizeId() == null ? other.getPrizeId() == null : this.getPrizeId().equals(other.getPrizeId()))
				&& (this.getGroupId() == null ? other.getGroupId() == null
						: this.getGroupId().equals(other.getGroupId()))
				&& (this.getPrizeNumber() == null ? other.getPrizeNumber() == null
						: this.getPrizeNumber().equals(other.getPrizeNumber()))
				&& (this.getPrizeWinner() == null ? other.getPrizeWinner() == null
						: this.getPrizeWinner().equals(other.getPrizeWinner()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getPrizeId() == null) ? 0 : getPrizeId().hashCode());
		result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
		result = prime * result + ((getPrizeNumber() == null) ? 0 : getPrizeNumber().hashCode());
		result = prime * result + ((getPrizeWinner() == null) ? 0 : getPrizeWinner().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_prize_group_info
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", prizeId=").append(prizeId);
		sb.append(", groupId=").append(groupId);
		sb.append(", prizeNumber=").append(prizeNumber);
		sb.append(", prizeWinner=").append(prizeWinner);
		sb.append("]");
		return sb.toString();
	}
}