package com.wistronits.wistlotto.model.tables;

import java.io.Serializable;

public class TSysInfo extends TSysInfoKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_sys_info.sys_value
	 * 
	 * @mbg.generated
	 */
	private String sysValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table t_sys_info
	 * 
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_sys_info.sys_value
	 * 
	 * @return the value of t_sys_info.sys_value
	 * @mbg.generated
	 */
	public String getSysValue() {
		return sysValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_sys_info.sys_value
	 * 
	 * @param sysValue the value for t_sys_info.sys_value
	 * @mbg.generated
	 */
	public void setSysValue(String sysValue) {
		this.sysValue = sysValue == null ? null : sysValue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_sys_info
	 * 
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		TSysInfo other = (TSysInfo) that;
		return (this.getSysKey() == null ? other.getSysKey() == null : this.getSysKey().equals(other.getSysKey()))
				&& (this.getSysValue() == null ? other.getSysValue() == null
						: this.getSysValue().equals(other.getSysValue()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_sys_info
	 * 
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSysKey() == null) ? 0 : getSysKey().hashCode());
		result = prime * result + ((getSysValue() == null) ? 0 : getSysValue().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_sys_info
	 * 
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", sysValue=").append(sysValue);
		sb.append("]");
		return sb.toString();
	}
}