package com.wistronits.wistlotto.model.tables;

import java.io.Serializable;

public class TWinInfo implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_win_info.emp_id
	 * @mbg.generated
	 */
	private String empId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_win_info.prize_id
	 * @mbg.generated
	 */
	private String prizeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_win_info.win_time
	 * @mbg.generated
	 */
	private String winTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_win_info.emp_id
	 * @return  the value of t_win_info.emp_id
	 * @mbg.generated
	 */
	public String getEmpId() {
		return empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_win_info.emp_id
	 * @param empId  the value for t_win_info.emp_id
	 * @mbg.generated
	 */
	public void setEmpId(String empId) {
		this.empId = empId == null ? null : empId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_win_info.prize_id
	 * @return  the value of t_win_info.prize_id
	 * @mbg.generated
	 */
	public String getPrizeId() {
		return prizeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_win_info.prize_id
	 * @param prizeId  the value for t_win_info.prize_id
	 * @mbg.generated
	 */
	public void setPrizeId(String prizeId) {
		this.prizeId = prizeId == null ? null : prizeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_win_info.win_time
	 * @return  the value of t_win_info.win_time
	 * @mbg.generated
	 */
	public String getWinTime() {
		return winTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_win_info.win_time
	 * @param winTime  the value for t_win_info.win_time
	 * @mbg.generated
	 */
	public void setWinTime(String winTime) {
		this.winTime = winTime == null ? null : winTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		TWinInfo other = (TWinInfo) that;
		return (this.getEmpId() == null ? other.getEmpId() == null : this.getEmpId().equals(other.getEmpId()))
				&& (this.getPrizeId() == null ? other.getPrizeId() == null
						: this.getPrizeId().equals(other.getPrizeId()))
				&& (this.getWinTime() == null ? other.getWinTime() == null
						: this.getWinTime().equals(other.getWinTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getEmpId() == null) ? 0 : getEmpId().hashCode());
		result = prime * result + ((getPrizeId() == null) ? 0 : getPrizeId().hashCode());
		result = prime * result + ((getWinTime() == null) ? 0 : getWinTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", empId=").append(empId);
		sb.append(", prizeId=").append(prizeId);
		sb.append(", winTime=").append(winTime);
		sb.append("]");
		return sb.toString();
	}
}