package com.wistronits.wistlotto.model.tables;

import java.util.ArrayList;
import java.util.List;

public class TWinInfoCriteria {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	public TWinInfoCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andEmpIdIsNull() {
			addCriterion("emp_id is null");
			return (Criteria) this;
		}

		public Criteria andEmpIdIsNotNull() {
			addCriterion("emp_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmpIdEqualTo(String value) {
			addCriterion("emp_id =", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotEqualTo(String value) {
			addCriterion("emp_id <>", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdGreaterThan(String value) {
			addCriterion("emp_id >", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdGreaterThanOrEqualTo(String value) {
			addCriterion("emp_id >=", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdLessThan(String value) {
			addCriterion("emp_id <", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdLessThanOrEqualTo(String value) {
			addCriterion("emp_id <=", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdLike(String value) {
			addCriterion("emp_id like", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotLike(String value) {
			addCriterion("emp_id not like", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdIn(List<String> values) {
			addCriterion("emp_id in", values, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotIn(List<String> values) {
			addCriterion("emp_id not in", values, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdBetween(String value1, String value2) {
			addCriterion("emp_id between", value1, value2, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotBetween(String value1, String value2) {
			addCriterion("emp_id not between", value1, value2, "empId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdIsNull() {
			addCriterion("prize_id is null");
			return (Criteria) this;
		}

		public Criteria andPrizeIdIsNotNull() {
			addCriterion("prize_id is not null");
			return (Criteria) this;
		}

		public Criteria andPrizeIdEqualTo(String value) {
			addCriterion("prize_id =", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdNotEqualTo(String value) {
			addCriterion("prize_id <>", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdGreaterThan(String value) {
			addCriterion("prize_id >", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdGreaterThanOrEqualTo(String value) {
			addCriterion("prize_id >=", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdLessThan(String value) {
			addCriterion("prize_id <", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdLessThanOrEqualTo(String value) {
			addCriterion("prize_id <=", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdLike(String value) {
			addCriterion("prize_id like", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdNotLike(String value) {
			addCriterion("prize_id not like", value, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdIn(List<String> values) {
			addCriterion("prize_id in", values, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdNotIn(List<String> values) {
			addCriterion("prize_id not in", values, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdBetween(String value1, String value2) {
			addCriterion("prize_id between", value1, value2, "prizeId");
			return (Criteria) this;
		}

		public Criteria andPrizeIdNotBetween(String value1, String value2) {
			addCriterion("prize_id not between", value1, value2, "prizeId");
			return (Criteria) this;
		}

		public Criteria andWinTimeIsNull() {
			addCriterion("win_time is null");
			return (Criteria) this;
		}

		public Criteria andWinTimeIsNotNull() {
			addCriterion("win_time is not null");
			return (Criteria) this;
		}

		public Criteria andWinTimeEqualTo(String value) {
			addCriterion("win_time =", value, "winTime");
			return (Criteria) this;
		}

		public Criteria andWinTimeNotEqualTo(String value) {
			addCriterion("win_time <>", value, "winTime");
			return (Criteria) this;
		}

		public Criteria andWinTimeGreaterThan(String value) {
			addCriterion("win_time >", value, "winTime");
			return (Criteria) this;
		}

		public Criteria andWinTimeGreaterThanOrEqualTo(String value) {
			addCriterion("win_time >=", value, "winTime");
			return (Criteria) this;
		}

		public Criteria andWinTimeLessThan(String value) {
			addCriterion("win_time <", value, "winTime");
			return (Criteria) this;
		}

		public Criteria andWinTimeLessThanOrEqualTo(String value) {
			addCriterion("win_time <=", value, "winTime");
			return (Criteria) this;
		}

		public Criteria andWinTimeLike(String value) {
			addCriterion("win_time like", value, "winTime");
			return (Criteria) this;
		}

		public Criteria andWinTimeNotLike(String value) {
			addCriterion("win_time not like", value, "winTime");
			return (Criteria) this;
		}

		public Criteria andWinTimeIn(List<String> values) {
			addCriterion("win_time in", values, "winTime");
			return (Criteria) this;
		}

		public Criteria andWinTimeNotIn(List<String> values) {
			addCriterion("win_time not in", values, "winTime");
			return (Criteria) this;
		}

		public Criteria andWinTimeBetween(String value1, String value2) {
			addCriterion("win_time between", value1, value2, "winTime");
			return (Criteria) this;
		}

		public Criteria andWinTimeNotBetween(String value1, String value2) {
			addCriterion("win_time not between", value1, value2, "winTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_win_info
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_win_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}